/**
 * @author caiwenduio
 * @file type
 */

const CHANGE_TABLEDATA = 'CHANGE_TABLEDATA';

const CHANGE_TABLELOADING = 'CHANGE_TABLELOADING';

const GET_TABLEDATA = 'GET_TABLEDATA';

const CHANGE_MODAL = 'CHANGE_MODAL';

const DELETE_CLASSIFY = 'DELETE_CLASSIFY';

const ADD_EDIT_SAVE = 'ADD_EDIT_SAVE';

export default {
  CHANGE_TABLEDATA,
  CHANGE_TABLELOADING,
  GET_TABLEDATA,
  CHANGE_MODAL,
  DELETE_CLASSIFY,
  ADD_EDIT_SAVE,
};
