/**
 * @author caiwenduio
 * @file 全局的type
 */

const GLOBAL_APPEND_USERINFO = 'GLOBAL_APPEND_USERINFO';
const GLOBAL_CHANGE_LAYOUT = 'GLOBAL_CHANGE_LAYOUT';
const GLOBAL_GETUSERINFO = 'GLOBAL_GETUSERINFO';
const GLOBAL_LOGOUT = 'GLOBAL_LOGOUT';
const GLOBAL_CHANGE_QINIU = 'GLOBAL_CHANGE_QINIU';
const GLOBAL_GET_QINIU_TOKEN = 'GLOBAL_GET_QINIU_TOKEN';
const GLOBAL_UPLOAD = 'GLOBAL_UPLOAD';

export default {
  GLOBAL_APPEND_USERINFO,
  GLOBAL_CHANGE_LAYOUT,
  GLOBAL_GETUSERINFO,
  GLOBAL_LOGOUT,
  GLOBAL_CHANGE_QINIU,
  GLOBAL_GET_QINIU_TOKEN,
  GLOBAL_UPLOAD,
};
